### ISSUE TITLE
some bugs for your code

### ISSUE THREAD

**Issue by czy341181** [Willy0919/DDMP-3D#1]
Thanks for your great work!

I have some questions.

1.when I use sh train.sh, I got  the following bug.

File "/data1/czy/AAAI/DDMP/DDMP-3D/lib/rpn_util.py", line 154, in generate_anchors
    raise ValueError('Non-used anchor #{} found'.format(aind))
ValueError: Non-used anchor #0 found

2.But when I use sh train_xyz.sh ,there is no bug.

When I run sh train_dep_xyz.sh, no such file:  training/depth_2/2189.pkl'
Can you provide pkl files of xyz map?

**Comment by Willy0919** [comment]
@czy341181 Thanks for your attention.
1. The only difference between train.sh and train_xyz.sh is the way to read the input depth map, if you could not find the issues leading to 'non-used anchor', you can just modify the line 96 in imdb_util_xyz.py for common depth map input.
2. 'xyz_map' just replace the  the first two dimensions of depth map with x and y values on 2D plane.

**Comment by czy341181** [comment]
Thanks, can you modify your code? I got another error. 


 File "/data1/czy/AAAI/DDMP/DDMP-3D/models/resnet_mod.py", line 159, in forward
    out += residual
RuntimeError: The size of tensor a (57) must match the size of tensor b (110) at non-singleton dimension 3

**Comment by Willy0919** [comment]
@czy341181 Sorry for the bugs, I have fixed it, and you can use train.sh to run.
