### ISSUE TITLE
RuntimeError:  view size is not compatible with input tensor's size and stride ... 

### ISSUE THREAD

**Issue by songlin** [Willy0919/DDMP-3D#4]
Hi ,

Thank you for the great work!

When I try to do training on a single GPU 3090 24G, I got following error
```
return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "scripts/train.py", line 215, in <module>
    main(sys.argv[1:])
  File "scripts/train.py", line 149, in main
    total_loss.backward()
  File "/home/songlin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/songlin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/home/songlin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/function.py", line 87, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
  File "/home/songlin/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/function.py", line 204, in wrapper
    outputs = fn(ctx, *args)
  File "/home/songlin/Projects/dgmn/maskrcnn_benchmark/layers/dcn/deform_conv_func.py", line 128, in backward
    cur_im2col_step
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
Here is what i changed in `train.sh`:
```
CUDA_VISIBLE_DEVICES=0 ....
```
and changed `batch_size` to 2 in `config/depth_ddmp.py`
```
conf.batch_size = 2 # 5*8
```
then i run
```
sh train.sh
```

Is there anything i missed?  i think my memory is enough for batch_size=2. But the error happens as above.
By the way, the training can run successfully with batch_size=1 but only takes about 9G memory

**Comment by Willy0919** [comment]
I did not encountered the error, but I think that it may happen with the use of "view()" function, you can localize the "view()" function and use xx.contiguous().view() instead.

**Comment by songlin** [comment]
Sorry, I don't know where to look into this issue. If you look at the above error function stack, there is even no .view() function invoked.
There are literally hundreds of ".view()" calls, both in DDMP-3D and dgmn's modified maskrcnn_benmark when i gloablly search the keyword. Do I need modify all of them ?

**Comment by Willy0919** [comment]
I have listed my environment configure in readme, you can first check your environments. If it still reports errors, I suggest that you first modify the functions in models/resnet_ddmp.py.

**Comment by songlin** [comment]
Ok, I will look into that. Thanks.

**Comment by songlin** [comment]
I solved the problem by replacing view with reshape.
```
sed -i 's/view/reshape/g' deform_conv_cuda.cpp
```

**Comment by JohanCao** [comment]
> I solved the problem by replacing view with reshape.
> 
> ```
> sed -i 's/view/reshape/g' mmdet/ops/dcn/src/deform_conv_cuda.cpp
> ```

HI songlin,

Could you give more details on how you solve this issue? As  I can not find "deform_conv_cuda.cpp"

Thanks!
Johan

**Comment by songlin** [comment]
Actually it's `maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.cu` located in the referenced project `dgmn`

**Comment by JohanCao** [comment]
> Actually it's `maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.cu` located in the referenced project `dgmn`

That's very helpful, thank you very much!

**Comment by syy-whu** [comment]
@songlin hello, i replace all view with reshape in the deform_conv_cuda.cu, but it did not work. could you send me revised code, thanks very much!
